### ISSUE TITLE
Blocked user still sees '...' in conversation with his blocker

### ISSUE THREAD

**Issue by Brice-W** [loki-project/session-desktop#1040]
**Describe the bug**
A = Desktop
B = iOS
I have a conversations between A and B.
A blocks B.
When A is writing in the text area of the conversation, B sees the ‘…’ in the conversation.

**To Reproduce**
Having a conversation started between A and B.
A blocks B
A writes in the text area of his conversation with B.
B has the conversation with A open and sees the '...'

**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.

**Other information (please complete the following information):**

* Device: A is Desktop (tested on Dev and MacOS versions), B is Simulator of iPhone 11 Pro Max
* OS: MacOS 10.15.4, iOS 13.4
* Session Version or Git commit hash: 1.0.5 on MacOS

**Comment by Bilb** [comment]
@Brice-W this should be fixed on v1.4.3. Feel free to reopen if needed
