### ISSUE TITLE
Can't mark message as read

### ISSUE THREAD

**Issue by neuroscr** [loki-project/session-desktop#1045]
**Describe the bug**
Nothing I can do will mark this message as read:
I've tried
- clicking the convo in the left col
- scrolling mouse wheel
- clicking on "Type your message"

**To Reproduce**
have a tall window or convo with few messages
might need a restart too

**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.
![Screen Shot 2020-04-02 at 3 24 15 PM](https://user-images.githubusercontent.com/1224671/78305561-0ef5fb80-74f6-11ea-8c87-c42f13c76e8c.png)

**Other information (please complete the following information):**

* Device: Mac Pro
* OS: 10.14
* Session Version or Git commit hash: 90d2bbb3385ccbef9622fba2d045aac9fec1c5a8

**Comment by Bilb** [comment]
@neuroscr This should be fixed on v1.4.3. Can you please close this issue if yes?

**Comment by neuroscr** [comment]
Yes, it's better. No "mark all as read" in the context menu, but this is better than what we had.
