### ISSUE TITLE
Session v1.0.6 doesn't work on Windows/MacOS

### ISSUE THREAD

**Issue by HostFat** [loki-project/session-desktop#1055]
I've installed it over v1.0.5, and it remains on this status.

![image](https://user-images.githubusercontent.com/644416/78330878-3647d980-7585-11ea-9138-0355981479f2.png)

I've then uninstalled it, and installed it again, the v1.0.6, but it remains stuck on the same way.

**Comment by neuroscr** [comment]
I got the same when I upgraded
![Screen Shot 2020-04-03 at 3 07 34 AM](https://user-images.githubusercontent.com/1224671/78349411-72187a00-7558-11ea-95de-e51753dbf3ab.png)

**Comment by HostFat** [comment]
The new v1.0.6 works.
