### ISSUE TITLE
@ Mentions: preview of last message under group name display the Session ID instead of username

### ISSUE THREAD

**Issue by Brice-W** [loki-project/session-desktop#1059]
**Describe the bug**

In the Session tab, in the list of conversations, under the group name, there is a preview of the last message. If that last message is a mention, it displays the ID after @ instead of the username

**To Reproduce**

In a group, send a message starting with a @mention

**Screenshots or Logs**

<img width="295" alt="Screen Shot 2020-04-06 at 3 11 31 pm" src="https://user-images.githubusercontent.com/62363622/78620935-a37ca700-78c4-11ea-8315-ac2df38d8323.png">

**Other information (please complete the following information):**

* Device: PC, Mac
* OS: [e.g. Ubuntu 16.04, Windows 10]
* Session Version or Git commit hash: 1.0.6

**Comment by konstantinullrich** [comment]
I'll take a look, what I can do.
