### ISSUE TITLE
Allow custom URIs to open up Session

### ISSUE THREAD

**Issue by vincentbavitz** [loki-project/session-desktop#1066]
URIs of type
``session-open:<pubkey>`` for example would launch session and initiate a friend request / session with ``pubkey``.

Will be possible & seamless when the app uses global Redux for all conversation events.

**Comment by Mikunj** [comment]
I would rather it just open up the conversation where you can initiate the friend request yourself, otherwise someone can trick you into clicking the url and automatically become friends with you

**Comment by Bilb** [comment]
relates https://github.com/loki-project/session-desktop/issues/1072
