### ISSUE TITLE
Read messages marked as unread

### ISSUE THREAD

**Issue by nooblag** [loki-project/session-desktop#1070]
**Describe the bug**
Not sure if a bug, but the last messages seen and read for a specific user still appear as unread.

**To Reproduce**
Potential steps to reproduce the behaviour:
1) Open Session chat (test system in on Windows 10);
2) Conversation with user, and they send the last message (i.e. I do not reply);
3) Their last message which was seen/read is not marked as read, and UI informs "1 unread message" still

**Screenshots or Logs**

![unread](https://user-images.githubusercontent.com/1122344/78785916-462f4580-79eb-11ea-93e3-4dc7e94fab5d.PNG)

You can see above that this test message was received 21st March, and Session Chat has been opened/closed many times since then, message still appears as unread.

**Other information (please complete the following information):**

* Device: [e.g. PC, Mac] PC.
* OS: [e.g. Ubuntu 16.04, Windows 10] Windows 10.
* Session Version or Git commit hash: 1.0.5

**Comment by neuroscr** [comment]
Maybe related to #1045

**Comment by nooblag** [comment]
Sounds like it.

**Comment by nooblag** [comment]
I think this has been fixed?
