### ISSUE TITLE
contextIsolation is false - security issue

### ISSUE THREAD

**Issue by good-lly** [loki-project/session-desktop#1078]
Even when you use nodeIntegration: false to enforce strong isolation and prevent the use of Node primitives, contextIsolation must also be used.

https://github.com/electron/electron/blob/master/docs/tutorial/security.md#3-enable-context-isolation-for-remote-content

is there any reason for you to disable contextIsolation?

**Comment by neuroscr** [comment]
Signal designed their app to require that. As to what reasons, you'd have to ask them.

We reviewed it and it would be a major undertaking to change this aspect. We would like to, but not sure when that will happen on the time line.
