### ISSUE TITLE
Link Device button does nothing

### ISSUE THREAD

**Issue by Brice-W** [loki-project/session-desktop#1079]
**Describe the bug**

Trying to pair my Desktop device after deleting my account does nothing.
I had that issue while trying to pair a Desktop device to an other device. For tests purpose, the issue can be reproduced without trying to pair to a primary device.

**To Reproduce**
Start with an existing session on Desktop.
Delete the account, Session restarts
On the start screen, select ‘Sign In’ => ‘Link Device to Existing Session ID’ => enter a session ID, click on ‘Link Device’
It displays ‘…’ a couple of seconds and after ‘…’ disappear and nothing happens. Clicking again on ‘Link Device' does nothing’
If I click on ‘Create Account’ tab and back to ‘Sign In’ and try again it seems to work normally.

**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.

**Other information (please complete the following information):**

* Device: [e.g. PC, Mac]
* OS: either macOS and windows
* Session Version or Git commit hash: 85e5a067c98a02267034d99fb3622d68b53de609

**Comment by rdsu-pt** [comment]
Same here!

**Comment by neuroscr** [comment]
@rdsu-pt what version of Session are you on?

**Comment by rdsu-pt** [comment]
@neuroscr , I just download the latest version, 1.0.6...

**Comment by Mikunj** [comment]
1.0.7 is the new version

**Comment by rdsu-pt** [comment]
After install v1.0.7, Session automatically opened with my Session ID.

**Comment by KeeJef** [comment]
Was not able to reproduce this issue with desktop version 1.0.8 are you still facing this with the latest update? are both devices in the linking screen when attempting the link?
