### ISSUE TITLE
Closed group creation: Desktop sends ‘Please accept…’ message to other members

### ISSUE THREAD

**Issue by Brice-W** [loki-project/session-desktop#1080]
**Describe the bug**

When creating a Closed group that includes Desktop devices, the Desktop devices send the ‘Please accept…’ message to all the members they are not friend with.

**To Reproduce**
In this example A, B and C can be either platform, D is Desktop.
Device A is friend with B, C and D.
B, C and D aren’t friend with each other.
A creates a private group with B, C and D. Once the group is created, D sends ‘Please accept to enable messages to be synced across devices’ to B and C.

**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.

**Other information (please complete the following information):**

* Device: [e.g. PC, Mac]
* OS: [e.g. Ubuntu 16.04, Windows 10]
* Session Version or Git commit hash:
Desktop: 85e5a067c98a02267034d99fb3622d68b53de609
iOS: e24daf7b67184f717035a15374e4bb89479f9cc5
Android: 11b5c78e3eb82085fd61e3f0a259af982a0f9b63
Android service: 1e1cea15013987f3784be78e3636e2ad6f102912

**Comment by Bilb** [comment]
This string `Please accept...` is no longer written by Session Desktop
