### ISSUE TITLE
Incomplete dependency list for Session 1.0.6 Debian package?

### ISSUE THREAD

**Issue by beantaco** [loki-project/session-desktop#1092]
Session 1.0.6 Debian package lists the following dependencies:

~~~
$ dpkg-deb --info session-messenger-desktop-linux-amd64-1.0.6.deb | grep 'Depends:'
 Depends: libnotify4, libappindicator1, libxtst6, libnss3, libasound2, libxss1
~~~

However, libc6 (>= 2.25) also seems to be required, so the dependency list may be incomplete. See #1082.

An update of the dependency list would facilitate proper installation. Otherwise, Session might install with no apparent problems but won't run.

**Comment by beantaco** [comment]
I made Session Desktop 1.0.6 and 1.0.9 run on Tails 4.3 after installing the following:

- session-messenger-desktop
- libappindicator1 (0.4.92-7)
- libdbusmenu-gtk4 (18.10.20180917~bzr490+repack1-1)
- libindicator7 (0.5.0-4)

libappindicator1 is a dependency of session-messenger-desktop. libdbusmenu-gtk4 and libindicator7 are dependencies of libappindicator1.

libc6 (>= 2.25) is pre-installed in Tails 4.3, and as mentioned previously seems to be a dependency of session-messenger-desktop. What other packages are dependencies of session-messenger-desktop but are not listed as a dependency?

**Comment by beantaco** [comment]
After a very quick search of the code, I couldn't find any indication that Session calls any libc6 libraries. The code is JS not C. However, I suggest that someone with more knowledge of libraries and Session's code confirm this.

I guess it is possible the libc6 error is triggered by one or more Session dependencies and not by Session itself. In this case, it is beyond the scope of Session to fix this issue.

**Comment by majestrate** [comment]
libc6 is required by electron

**Comment by Bilb** [comment]
libc6 is a fairly central library on a unix system, the issue is more related to the version not being high enough (>= 2.25).
The easiest way to fix this issue is to update the OS with one having a more recent preinstalled libc6 version.
