### ISSUE TITLE
Show Seed  Hang

### ISSUE THREAD

**Issue by SH10151-LOIC** [loki-project/session-desktop#1097]
**Describe the bug**
The messenger hangs when trying to show seed words.

**To Reproduce**
100% of the time I can reproduce this solely by clicking the button to show the seeds. All other buttons work.

**Other information (please complete the following information):**

* Device: PC
* OS: Windows 10 Pro Version 1909 (fully patched)
* Session Version 1.0.6 and 1.0.7

**Comment by KeeJef** [comment]
This is not happening for me on Session 1.0.8, Can you update and see if it persists?
