### ISSUE TITLE
Unable to link to more than one secondary device

### ISSUE THREAD

**Issue by thelovebug** [loki-project/session-desktop#1104]
**Describe the bug**
I created my Session ID on the AppImage version of the app (v1.0.7).  I was then able to Link to my existing account on my Android device (Google Play, v1.1.0).  I then wanted to add my Android tablet (same application version) but the Link New Device button is disabled.

**To Reproduce**
1. Create new Session ID on the desktop version.
2. On Desktop, go to Settings, Devices, and click Link New Device.
3. On my first Android device, open Session and tap "Link to an existing account"
4. On my first Android device, tap on Scan QR Code, and scan the code from the Desktop.
5. Go through authorisation steps, device is now linked successfully.
6. On Desktop, go to Settings, Devices (to link second Android device)
7. The "Link New Device" button is disabled.

**Screenshots or Logs**
_button enabled with no linked devices_
![Screenshot from 2020-04-25 20-38-00](https://user-images.githubusercontent.com/2915687/80289145-b3094600-8734-11ea-9f44-396f409ba300.png)

_button disabled with one linked device_
![Screenshot from 2020-04-25 20-39-53_redacted](https://user-images.githubusercontent.com/2915687/80289202-12675600-8735-11ea-84b5-973aa44ce962.png)

**Other information (please complete the following information):**

* Device: Linux PC
* OS: Ubuntu 20.04
* Session Version or Git commit hash: Desktop 1.0.7 (AppImage), Mobile 1.1.0 (Google Play)

**Comment by neuroscr** [comment]
We only allow one linked device currently

**Comment by thelovebug** [comment]
Thanks for the update.  That makes sense now.

Can this please be added to the FAQ, as the wording of "Sync Across Devices" and the "Devices" tab on the Desktop Settings implies multiple.

Thanks! 😁

**Comment by KeeJef** [comment]
I have told the team to update the FAQ to make this more clear
