### ISSUE TITLE
Allow unlinking from slave to master

### ISSUE THREAD

**Issue by vincentbavitz** [loki-project/session-desktop#1111]
We have the issue that if a user links and unlinks many devices, we still send messages to all unlinked devices.

![linked_devices](https://user-images.githubusercontent.com/58160433/80682912-b1f66100-8b06-11ea-981c-621edb4c1cb3.png)

We no longer use ``getStaleDeviceIdsForNumber`` to grab unlinked pubkeys for users.
Ideally we'd be able to send an unlinking request from a slave to a master with signature of the secondary device which removes the record on the master's side.
In this way, when a user deletes their slave it's not permanently listed as a valid linked device.

**Comment by KeeJef** [comment]
Closed with partial solution, should be reopened if issue re-presents
