### ISSUE TITLE
Airgapped Usage

### ISSUE THREAD

**Issue by xloem** [loki-project/session-desktop#1115]
Hey, I was wondering how conducive the Session protocol is to usage across an air gap, or at least to verify message signatures on another device.  Do you think this would be very difficult in its present state?

**Comment by KeeJef** [comment]
Currently there is no way to save individual signed and encrypted messages, transfer them past the airgap and then rebroadcast them to the network on the other side although technically it would be possible. There are no import message features either to verify messages that were signed on an airgapped computer.

So overall i would say, its not conducive to use over an airgap , and it would be very difficult to do in its current state. Although it is probably possible.
