### ISSUE TITLE
Linking with iOS device fails.

### ISSUE THREAD

**Issue by JicKud** [loki-project/session-desktop#1123]
The flow on the desktop app shows the device linked with the correct three word code, but the iOS app never moves past the "waiting for authorizaton screen".

**Comment by KeeJef** [comment]
We rolled out a new iOS release which overhauled some of the multi device code, about a week ago, are you still experiencing this with the latest release?

**Comment by JicKud** [comment]
Hi. Thanks for your message. This is working fine now.
