### ISSUE TITLE
macOS: hang and CPU spikes when clicking "Show Seed" button in Settings

### ISSUE THREAD

**Issue by foss-** [loki-project/session-desktop#1125]
macOS 10.15.4
Session 1.0.7

**Describe the bug**
Session becomes unresponsive and CPU spikes for both Session and Session Helper

**To Reproduce**
- Open Session on macOS
- navigate to settings and click "Show Seed" button
- always reproducible, Session has to be force quit

**Screenshot**
![cpu spikes](https://user-images.githubusercontent.com/5708172/81551936-eda0ee80-9382-11ea-919d-298151549b29.png)

**Comment by vincentbavitz** [comment]
Is this strictly on Secondary Device? If so, fix is in next relrease.

**Comment by foss-** [comment]
In Session 1.0.8 on macOS 10.15.4 I no longer see the "Show Seed" button. The "Unlink Device" is the only button now.
