### ISSUE TITLE
Antivirus detects the setup.exe as mallware

### ISSUE THREAD

**Issue by Billkyriaf** [loki-project/session-desktop#1149]
Windows Defender detects the setup.exe as malware as soon as it downloads. The exact message is:
PUA:Win32/InstallCore
Alert level: Low
Category: Potentially Unwanted Software
Details: This program has potentially unwanted behavior.

After allowing the app through the firewall the setup run correctly.

This happens every time I download the .exe either from GitHub or the website.

* Device: Windows Laptop
* OS: Windows 10 pro 2004 OS built 19041.264 (insider build)
* Windows Defender version 1.317.113.0
* Session V 1.0.8 Desktop

**Comment by KeeJef** [comment]
Which Antivirus software ? What Platform? What version of Session?

**Comment by Billkyriaf** [comment]
> Which Antivirus software ? What Platform? What version of Session?

Sorry for that I updated the info

**Comment by D3191** [comment]
Here is a [virustotal report.](https://www.virustotal.com/gui/file/7517911ec6918ad5ae6a99ad85a09f8a00ba1fd69c8e8cd9ae178bec165bb9df/detection)

It looks like this is limited to windows defender.

**Comment by KeeJef** [comment]
I've filed a false detection report with Microsoft, hopefully they update their definition soon

**Comment by alefvanoon** [comment]
![image](https://user-images.githubusercontent.com/53198048/104764414-9f978280-577c-11eb-955b-ce68453cfac5.png)
still have problem with win defender.😬
