### ISSUE TITLE
emoji section grow off screen

### ISSUE THREAD

**Issue by danrobi11** [loki-project/session-desktop#1164]
Hello
session-messenger-desktop-linux-x86_64-1.0.9.AppImage
When clicking on the emoji icon to open the emoji section, the emoji section grow off the screen and so is the emoji icon (open/close)
We have to press 'tab' in order to have access to the emoji icon (open/close)
Regardless of the resolution same result. Tested with 1360x768 and 1920x1080

**Comment by Bilb** [comment]
Hey,
This should be fixed with https://github.com/loki-project/session-desktop/pull/1322 which will be in the next release

**Comment by danrobi11** [comment]
This issue is fixed with v1.3.0 Thanks for the fix. Therefore closing
