### ISSUE TITLE
Contact receives messages from another ID when I write from the Desktop app

### ISSUE THREAD

**Issue by 123chuck123** [loki-project/session-desktop#1181]
**Describe the bug**
I use Session on my Android Device and the Desktop Version on my Arch Linux Gnome System.
Android Primary device Desktop secondary device. Phone and desktop are linked with same ID.
Lets say I am writing with a contact from my android device. As soon as I start writing from the desktop app my contact receives my messages under a new ID. So he has two conversations with me with two different IDs.  My name stays the same but no profil picture on the second ID. Why is this happening?. My contact got confused.
I tried it out with my other android device. And the same result.

**To Reproduce**
Link your Android device with desktop session. Continue conversation with your contact.
Result = Contact receives your messages from another ID.

* Device: Laptop
* OS: Arch Linux Gnome
* Session Version or Git commit hash: 1.0.9 installed from AUR: https://aur.archlinux.org/packages/session-desktop-appimage/

**Comment by neuroscr** [comment]
Every secondary device is actually given its own ID and we try to hide it and only show the primary. But if there’s a bug like you found, the true secondary device may show instead.

**Comment by Skelaton4** [comment]
I have also had a friend experience this same issue. He was on the latest session IOS, and windows.
![20200617_171709](https://user-images.githubusercontent.com/28955674/84951423-68fe6a00-b0be-11ea-9785-dfec91fb0e1b.jpg)

**Comment by Mikunj** [comment]
Please let us know if you still experience this in the new session versions. If you are then i will re-open this issue.
