### ISSUE TITLE
flatpak-session-helper stays runnning when closing session

### ISSUE THREAD

**Issue by danrobi11** [loki-project/session-desktop#1261]
Is  flatpak-session-helper  suppose to keep running when we close session? 
I dont see any session icon in my systray, normal?

**Comment by Mikunj** [comment]
It shouldn't, was this problem occurring on v1.0.9? We're going to release a fix for the other issue shortly in v1.1.2, can you test to see if this issue still occurs there. If it does then i'll look into it further.

**Comment by danrobi11** [comment]
Hello 
Same result with v1.1.2 flatpak-session-helper stays running after I close session 
I cant recall using the flatpak version before v1.1.0

**Comment by Mikunj** [comment]
We actually don't have support for system tray in session so this issue seems to be a flatpak bug.

**Comment by danrobi11** [comment]
Hello
Same here with v1.2.0

**Comment by danrobi11** [comment]
Are you guys sure that flatpak-session-helper is related with session? Because says running since jul 22 here. However, I havent tried session since I've opened this issue, 17 days ago.

**Comment by danrobi11** [comment]
Not related with session, therefore closing
