### ISSUE TITLE
"Note To Self " dupplication from Android

### ISSUE THREAD

**Issue by alexandrestein** [loki-project/session-desktop#1266]
**Describe the bug**
Message to myself are duplicated from my Android to my Linux device.

**To Reproduce**

1. Linux and Android synchronized, in my case Android is the root device but it's the same when Linux is root.
2. Send a message to your self

**Screenshots or Logs**
![Screenshot from 2020-07-17 17-06-45](https://user-images.githubusercontent.com/5431025/87801387-f369f300-c84f-11ea-8b0e-6f3e58746bf9.png)

This is a video of what is happening with the duplicated message time stamp being identical. Which make it very easy to patch if it can't be not fixed properly.
[Screencast from 17-07-2020 16:54:37.zip](https://github.com/loki-project/session-desktop/files/4938505/Screencast.from.17-07-2020.16.54.37.zip)

**Other information (please complete the following information):**

* Devices: 
  - Linux Debian 10 up to date with Session 1.1.2 (updated today)
  - Android 10 Session 1.3.0 (updated today)

**Comment by Bilb** [comment]
Fixing this for now as we disabled multi device until it is more reliable.
