### ISSUE TITLE
Mac download link invalid on website

### ISSUE THREAD

**Issue by arunsathiya** [loki-project/session-desktop#1269]
**Describe the bug**

The Mac app download link is invalid on the website. It points me to [this page](https://github.com/loki-project/session-desktop/releases/download/v1.1.1/session-messenger-desktop-mac-1.1.1.dmg) which is a 404.

**To Reproduce**

- Visit Session website.
- Click on the downloads section
- Click on `Mac`
- When redirected to [this page](https://github.com/loki-project/session-desktop/releases/download/v1.1.1/session-messenger-desktop-mac-1.1.1.dmg), notice that the page is not found - appears with the error code 404.

**Screenshots or Logs**

<img width="1680" alt="Screenshot 2020-07-18 at 07 46 29" src="https://user-images.githubusercontent.com/18581859/87842543-d1fa1d00-c8ca-11ea-80ac-764cfb08c5f7.png">

**Other information (please complete the following information):**

* Device: Mac
* OS: macOS
* Session Version or Git commit hash: 1.1.1?

**Comment by arunsathiya** [comment]
1.1.2 works from [this page](https://github.com/loki-project/session-desktop/releases/download/v1.1.2/session-messenger-desktop-mac-1.1.2.dmg). So, just a matter of updating the link on website to 1.1.2, I guess?

**Comment by Mikunj** [comment]
This should be fixed now :)
