### ISSUE TITLE
[Feature Request] "Read" status icon for messages in chats

### ISSUE THREAD

**Issue by gitmaker032** [loki-project/session-desktop#1276]
Issue: the icon "Message has been read" appears only in the chat list for the last message (two check marks in circles). However, in the chat itself, the message always receives only one icon - sent (one checkmark). The message does not change the status icon even after reading it (both users have read receipts enabled). This needs to be fixed - add message status icons for: delivered (two ticks without filling) and read (two ticks with filling) for all chat messages.

![h3Js4KyOer](https://user-images.githubusercontent.com/67278783/88186704-3bb55680-cc3e-11ea-916a-b4ff48d17fe8.png)
![SJ136qfU4u](https://user-images.githubusercontent.com/67278783/88186847-70c1a900-cc3e-11ea-83d8-644a223fc107.png)

OS: WIndows 10 (but it is also relevant for Android and Linux).
Session version: 1.1.2

**Comment by finnishbroccoli** [comment]
Same issue in Linux appimage ver 1.1.2

**Comment by Bilb** [comment]
Should be fixed on v1.4.3. Please close this issue if yes.
@gitmaker032 @finnishbroccoli
