### ISSUE TITLE
Windows Defender detects the installer, "session-messenger-desktop-win-1.2.1.exe" contains PUA:Win32/CoinMiner

### ISSUE THREAD

**Issue by tonyping** [loki-project/session-desktop#1314]
**Describe the bug**
Windows Defender reports that "session-messenger-desktop-win-1.2.1.exe" contains PUA:Win32/CoinMiner, found in the Session Desktop executable installer. 

**To Reproduce**
Steps to reproduce the behavior: Run a quick scan with Windows Defender w/ the latest threat definitions, or run a per-item scan on the .exe itself.

**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.

**Other information (please complete the following information):**

* Device: [e.g. PC, Mac] Lenovo Thinkpad running Windows 10 64-bit, the latest OS patches and security definitions are installed.
* OS: [e.g. Ubuntu 16.04, Windows 10] Windows 10 64-bit Pro, Version 2004 build 19041
* Session Version or Git commit hash: v1.2.1

**Comment by tonyping** [comment]
VirusTotal also reports that Windows Defender picks up the same threat detection:
https://www.virustotal.com/gui/file/c1cc600792e700e430101436292b0ca66e353932a4d49afffa7f4a62fac41f7b/detection

No other engines on VT have reported yet.

**Comment by neuroscr** [comment]
False positive. We have a proof of work system as an anti flooding system.
