### ISSUE TITLE
Temporary workaround for Multi-Device: Exclusivity

### ISSUE THREAD

**Issue by CyberFoxHax** [loki-project/session-desktop#1318]
According faq what happened with multi device. You had some issues with performance while using multiple devices.

As a temporary workaround would it help to make the device usage exclusive? Say, once you sign into your computer the mobile will be blocked from usage, (adding a button to sign out other clients).

This would be adequate workaround cause i rarely touch my phone while on the computer as such it doesn't need to constantly deliver messages there.

(I think this may already be possible already by signing out of one device and signing into another device, but i haven't tested it)

**Comment by KeeJef** [comment]
The issue with Multi device has more to do with keeping devices properly synced. The Signal protocol has an intricate process of Session management which makes this very difficult, we will be circling back around to multi device in a few months time. Restoring your account with the same seed on multiple devices will cause lots of issues (sessions getting out of Sync), so thats not recommended

**Comment by CyberFoxHax** [comment]
ok thanks
