### ISSUE TITLE
Can't use same account for session-desktop and session-android (Session out of sync)

### ISSUE THREAD

**Issue by schattenpanzer** [loki-project/session-desktop#1327]
**Describe the bug**
Logging into Session-desktop using your recovery seed from your phone throws Session out of sync

**To Reproduce**
1. make a session id and seed on two smartphones
2. start a conversation on one phone with the other phone user
3. sign in using recovery seed on session-desktop flatpak
4. the phone not associated with session-desktop goes haywire with restore/dismiss Session out of sync popups
5. further conversation can't continue

**Other information (please complete the following information):**
* Device: PC/Linux(flatpak), Android 10

Session Version or Git commit hash:
- Desktop, 1.2.1
- Android, 1.4.7
- iphone (latest os) (apple store)

I love the whole idea of Session and I really want to make it work, but I get tons of errors when I try to open it in android studio, so I'm not sure how I could even begin to contribute.

**Comment by Skelaton4** [comment]
Multi-Device support has been disabled for the time being. There were too many issues regarding the user experience, it will be coming back in a later version of the software.

**Comment by Mikunj** [comment]
As Skelaton said, we have disabled multi device functionality until we can find an approach which makes it more stable. For the time being it is recommended to use different session ids for your devices. Sharing a session id will cause these sync issues because of the way the protocol works
