### ISSUE TITLE
Application does not render non Latin fonts properly

### ISSUE THREAD

**Issue by ghost** [loki-project/session-desktop#1366]
### Bug Description

I'm using English interface but sometimes typing Cyrillic conversion. Non-english glyphs looks too small and ugly. Thoughts, application supports only Latin glyphs properly. Please add font settings or update current fonts to support other languages.
 
### Platform Info

App Version: v1.3.1
Operating System: Ubuntu Linux 20.04

**Comment by Mikunj** [comment]
Hey could you provide us a screenshot so we can look into this issue further?

**Comment by Bilb** [comment]
Closing this as the text looks fine to me in Cyrillic: 
![image](https://user-images.githubusercontent.com/1544279/103606660-13f74800-4f6b-11eb-9fde-28aaffee2d91.png)

This could have been fixed since the react refactor of the Session Conversation
