### ISSUE TITLE
Scrolling up to load more messages not working properly

### ISSUE THREAD

**Issue by kmltdr** [loki-project/session-desktop#1375]
**Describe the bug**
When I try to load older messages by scrolling up, they do load, but appear below newer messages. 
Example:
Let's say there are two hundred messages in conversation and messages 151-200 are loaded (I have no idea what is the number of messages per load, so let's say it's 50). 
When I scroll up to message 151, 50 older messages load, but order they appear in my conversation view is: 151, 152, ..., 199, 200, 101, 102,..., 149, 150. Also, I can't access messages 1-100, because nothing happens when I scroll up to message 151 again.

**To Reproduce**
Go to conversation with enough messages, scroll up to load older messages.

**Other information (please complete the following information):**

* Device: PC
* OS: Void 5.8.12_1 x86_64
* Session Version: session-messenger-desktop-linux-x86_64-1.4.0.AppImage

**Comment by Bilb** [comment]
Relates https://github.com/loki-project/session-desktop/issues/1392

Should be fixed on v1.4.3. Please close this issue if yes.
@kmltdr

**Comment by kmltdr** [comment]
It works correctly now. Thank you @Bilb.
