### ISSUE TITLE
[minor bug] Default download name is signal (instead of Session)

### ISSUE THREAD

**Issue by invalid-error** [loki-project/session-desktop#1391]
**Describe the bug**
When you download a media file from Session the auto-naming is **signal**-yyyy-mm-dd-*.*

**To Reproduce**
i.e. download any image from Session.

**Other information (please complete the following information):**

* Device: PC
* OS: Linux AppImage
* Session Version or Git commit hash: 1.4.1

**Comment by Bilb** [comment]
Should be fixed on v1.4.3. Please close this issue if yes.
@invalid-error

**Comment by Bilb** [comment]
Marking this as fixed. Feel free to reopen otherwise

**Comment by invalid-error** [comment]
Confirmed. Thanks @Bilb
