### ISSUE TITLE
Should entering a recovery phrase ever result in a different Session ID?

### ISSUE THREAD

**Issue by beantaco** [loki-project/session-desktop#1395]
I created a new Session account a while ago. Let's say Session Desktop showed me **123**. I recorded the recovery phrase, let's say it is **cute cat**.

However, when I cleared account data and re-entered the recovery phrase **cute cat** on Session Desktop, I obtain a different Session ID **456**.

Questions:
- Should entering a recovery phrase ever result in a different Session ID?
- Has the Session ID calculation method changed between versions of Session?

Version information:
- At time of Session ID creation: most likely 1.3.x but could be 1.4.x
- Currently installed version: 1.4.2

I don't recall whether I created the account on Session Android or Session Desktop, but I use the account on Session Desktop, and Session Android account data has been cleared. I have not attempted to use the account on multiple devices simultaneously.

**Comment by beantaco** [comment]
#961 describes an issue related to seeds and Session IDs when linking multiple devices together. If I understand it correctly, the issue suggests each device has its own seed and Session ID, but secondary devices show the primary device's recovery phrase and Session ID.

I believe I created my account on Session Android first and then moved it to Session Desktop using the recovery phrase. I made no attempt to link devices, and I believe device linking is currently disabled pending a fix, but my account may have briefly existed on two devices simultaneously.

Is there a chance this issue is due to multiple devices? Or is it something more fundamental like how keys and Session IDs are derived from the recovery phrase?

**Comment by beantaco** [comment]
Commit 6dc3582a1, merged into version 1.4.1, changes the identity key mechanism. I suspect this commit changes the way the Session ID is derived from a recovery phrase. However, I haven't confirmed this by using a recovery phrase on Session Desktop version 1.4.0, so I don't comment with certainty.

Assuming the English wordlist (1626 words), a recovery phrase excluding the checksum word (13th word), of 12 words, has 128 bits of information (more accurately it's 12 log2(1626)), which gets decoded into a 128-bit seed. The seed then forms part of a 256-bit Ed25519 private key, then from there the public key and Session ID are derived. (Aside: It follows that the strength of the private keys are only 128 bit.)

The change shown below modifies how the 128-bit seed is extended to form the 256-bit private key. Let's say the seed is a hex string `1234` (16 bits just to illustrate the example):

- Before the change, the seed is duplicated: `1234` -> `12341234`
- After the change, the seed is zero-padded: `1234` -> `12340000`

This change exists in:

- `libtextsecure/account_manager.js`
- `ts/components/session/RegistrationTabs.tsx`

~~~diff
   // handle shorter than 32 bytes seeds
   const privKeyHexLength = 32 * 2;
   if (seedHex.length !== privKeyHexLength) {
-    seedHex = seedHex.concat(seedHex);
+    seedHex = seedHex.concat('0'.repeat(32));
     seedHex = seedHex.substring(0, privKeyHexLength);
   }
~~~

The commit also converts to using x25519 keypair, which may also be contributing to the change in Session ID derivation.

Given the commit changes how the private key is derived from the seed, I suspect this therefore leads to a change in the derived Session ID.

Implications assuming the above suspicion is true:

- Pre-1.4.1 Session IDs are not recoverable from their recovery phrases using Session Desktop version 1.4.1 or later.
- Session users who have shared their pre-1.4.1 Session IDs with their contacts and then use their recovery phrase on Session Desktop 1.4.1 or later may become unreachable by their contacts.
- What is the best way forward: revert the Session ID derivation method to minimize damage to Session users with pre-1.4.1 Session IDs, or stick with the new derivation method and make everyone transition their Session IDs?

**Comment by nielsandriesse** [comment]
A while ago we improved the way we generate private keys by adding a hashing step. This adds some extra security. We're going to publish something about this so users can migrate if they want to :) .

**Comment by beantaco** [comment]
Given the change outlined in this issue breaks backward compatibility, it's concerning the change was merged into a minor release (1.4.0 -> 1.4.1) without much announcement, making me think the change is a bug.

Thanks for the info about the upcoming intentional change. Without knowing what the new method will do, hashing the seed may be better (at least methodically) than just duplicating or padding the 128-bit seed.

My understanding is the following private key derivation methods:

- 1.4.0 and earlier: the seed is duplicated
- 1.4.1 and 1.4.2: the seed is padded with zeros
- The new method: the seed is hashed?

Will Session IDs derived using the new method be given a different prefix? For example, Session IDs (hex strings) are currently given a prefix `05`, so will new Session IDs be given a new prefix?

If users want to share Session IDs reliably, which type of Session ID should users share right now (currently version 1.4.2 is the latest)? Or should users wait until the new method is introduced?

**Comment by nielsandriesse** [comment]
This is already the new method :) . The seed is 16 bytes of random data + 16 bytes of zeros. The hashing happens because we now generate an ED25519 key pair and then generate an X25519 key pair from that (before we directly generated an X25519 key pair).

The Session ID prefix won't change because Session IDs generated with the previous method and Session IDs generated with the new method can talk to eachother without issue. If you generated your Session ID with 1.4.1+ you can share that without worrying that it'll change again.

**Comment by beantaco** [comment]
Thanks for the clarification. I misunderstood before, but now I think I got it :+1: I'll start sharing the Session ID derived using version 1.4.1+.

**Comment by nielsandriesse** [comment]
Agreed! We'll be adding a notice to the app :)

**Comment by Bilb** [comment]
A notice was added on the latest release so I will close that one for now
