### ISSUE TITLE
Buttons at the bottom disappear when Session is offline

### ISSUE THREAD

**Issue by beantaco** [loki-project/session-desktop#1396]
When Session is disconnected/offline, the buttons at the bottom hide from view, including:
- night/day mode toggle
- start closed group
- clear data
- recovery seed

At the same time, a warning shoes at the top, on a green background when using night mode, warning about Session being disconnected.

Is this intentional or a bug?

Adjusting the window in any way does not affect visibility of the hidden buttons.

Version: 1.4.2

**Comment by Bilb** [comment]
Should be fixed on v1.4.3. Please close this issue if yes.
@beantaco

**Comment by beantaco** [comment]
The problem is fixed on 1.4.3 so I'll close the issue.
