### ISSUE TITLE
Debian Repository or automatic downloads with apt upgrade?

### ISSUE THREAD

**Issue by Danrancan** [loki-project/session-desktop#1397]
I am kind of new to get and git repos. I am using debian 10. I searched around and couldn't find any official repos to add session desktop to my sources.list file in debian. I would like to find a way to automatically update the session-desktop.deb file upon each new relase without having to manually download from the page and use dpkg to install it. Are there any official debian repositories for this app to add to my sources.list, and if not, is there any way to autoupdate this app (preferable using apt update && apt install) when new releases come out in the form of .deb files? Any help/advice/suggestions would be greatly appreciated!

**Comment by beantaco** [comment]
A Debian repo for Session has not been made available yet. Please see related issue #1096.

**Comment by jagerman** [comment]
Session packages *are* available in the Loki Debian repositories, for Debian 10 & sid, and Ubuntu 18.04/20.04/20.10.

You can set it up with:
```bash
sudo curl -so /etc/apt/trusted.gpg.d/loki.gpg https://deb.loki.network/pub.gpg
echo "deb https://deb.loki.network $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/loki.list
sudo apt update
sudo apt install session-desktop
```
after which you'll get updates via regular distribution updates.
