### ISSUE TITLE
Session and Signal mixed in contact entries.

### ISSUE THREAD

**Issue by feddnoai** [loki-project/session-desktop#1411]
OS: Unofficial LineageOS 16 --> Android 9
App version: 1.6.7.1 (1295)

Contact entries are being somewhat mixed. Session icon and "Signal-Call"...!?

Screenshot: https://abload.de/img/session-attachment-2oyj19.jpeg

**Comment by Bilb** [comment]
@feddnoai just to be sure, this is on the android app right?

**Comment by feddnoai** [comment]
Yes, that's right!

**Comment by Bilb** [comment]
@feddnoai can you please open the issue on the session android github https://github.com/loki-project/session-android/issues ?

**Comment by feddnoai** [comment]
Yes, thank you!
