### ISSUE TITLE
Sync message desktop and android

### ISSUE THREAD

**Issue by LorisTecnology** [loki-project/session-desktop#1425]
**Describe the bug**
When i send a message on Desktop i don't see the message on Android even when the person send me a message to me

**To Reproduce**

1. Open a chat
2. Send a message

You expect to see the message on your phone and viceversa

* Device: [PC and Android]
* OS: [Win 10 and Android 10]

**Comment by KeeJef** [comment]
Are you talking about two devices which are sharing the same Session ID?

**Comment by LorisTecnology** [comment]
yeeep exactly

**Comment by LorisTecnology** [comment]
i've seen on discord that the implementation will be ready in within a month

**Comment by KeeJef** [comment]
Multi device is not yet officially supported in any of the Session clients, We will be adding support for it soon. For now you should be able to receive the same messages on two devices with the same Session ID's , however you are likely to have issues in closed groups, and in 1-1 chats and closed groups sent messages will not be synced across devices
