### ISSUE TITLE
P2p messages leaking metadata

### ISSUE THREAD

**Issue by BeaudanBrown** [loki-project/session-desktop#251]
Currently the local server returns with 200 as soon as the request has been confirmed to hit `/v1/storage_rpc` with the `store` method, or rejects if it is incorrect
This means that someone who might not be friends with you can still use these responses to tell if you are online or not. It also means that if your session with someone is corrupted somehow when that person sends a p2p message to you it shows you as online and the message as successfully sent over p2p even though you would see nothing about the message
I think we should do 2 things
- Only respond with 200 for messages that have been successfully decrypted
- Do not respond to any p2p messages that result in failures to prevent from leaking status information to people we are not friends with

Would like to see what anyone else thinks

**Comment by Mikunj** [comment]
> Only respond with 200 for messages that have been successfully decrypted
which decryption are you talking about? The message content decryption? if so then that would make the logic very complex.

> Do not respond to any p2p messages that result in failures to prevent from leaking status information to people we are not friends with
I'm still unsure of this

**Comment by BeaudanBrown** [comment]
Ya the message content decryption and ya I think it will become complex, will need to have a chat about it
I definitely think we should be trying to minimise the responses we make so they are only for people we know we are friend with tho

**Comment by KeeJef** [comment]
P2P code has been removed so gonna yeet this
