### ISSUE TITLE
Look into debuglogs

### ISSUE THREAD

**Issue by sachaaaaa** [loki-project/session-desktop#260]
Make sure we're not sending logs to the signal online logs.

**Comment by BeaudanBrown** [comment]
From what I can tell debuglogs.org just lets you dump log files at it which are then publicly available from the link provided
https://debuglogs.org/7500853d014ac5271b6378f8572d55f260b9165419e4202549f98badc11fbf05
Will update the `Report an issue` link to direct to loki-messenger tho

**Comment by KeeJef** [comment]
Update on this ?

**Comment by BeaudanBrown** [comment]
Confirmed last week we are sending logs to a signal operated server
We had a cursory google and there doesn't seem to be a free alternative that isn't self hosted so we might need to look into setting that up to keep the same functionality
(but also there seems to be zero authentication on the signal debuglogs which are working great for us...)

**Comment by KeeJef** [comment]
This should all be removed now
