### ISSUE TITLE
Long polling delays connection status

### ISSUE THREAD

**Issue by BeaudanBrown** [loki-project/session-desktop#282]
**Describe the bug**
The connection status of the client is determined from the successful retrieval of messages
Since the addition of long polling, if the client doesn't have any messages the response from the snode will be delayed by 30 seconds
This means that if the client failed to connect to a retrieving snode for whatever reason, the disconnected banner will remain until either they receive a new message or 30 seconds passes

**To Reproduce**
Steps to reproduce the behaviour:
1. Successfully retrieve all your messages or create a new account which doesn't have any
2. Cause a retrieve messages request to fail somehow (cleanest way is to breakpoint http-resources.js line 94 and change connected to false)
3. Disconnected banner will remain for 30 seconds

**Comment by KeeJef** [comment]
this is not relevant anymore
