### ISSUE TITLE
The red circle next to the message is only partially visible

### ISSUE THREAD

**Issue by msgmaxim** [loki-project/session-desktop#302]
**Describe the bug**
Long message failed and it wasn't clear why. The red circle next to the message only partially visible. Seems to be a Mac problem.

**To Reproduce**
Send a long message to a friend on a Mac.

**Screenshots or Log files**

![Screen Shot 2019-06-13 at 1 13 10 pm](https://user-images.githubusercontent.com/2591783/59401314-a65e5680-8ddd-11e9-8905-aff653d3a077.png)

**Desktop (please complete the following information):**
 - macOS 10.13.6
 - v0.0.0-beta1 bea2e586799272bd3a5fdb4b00b242f77f18eb38

**Comment by KeeJef** [comment]
should be Fixed with the redesign
