### ISSUE TITLE
Auto Updates for Desktop

### ISSUE THREAD

**Issue by BeaudanBrown** [loki-project/session-desktop#312]
A few months ago signal introduced in app updating, we should see if we can hook this to update from our own source
Some relevant code
https://github.com/loki-project/loki-messenger/blob/development/ts/updater/common.ts#L81
https://github.com/loki-project/loki-messenger/blob/development/config/default.json#L10

**Comment by Mikunj** [comment]
We could point that to a file in this repo

**Comment by KeeJef** [comment]
Any updates on this ?

**Comment by KeeJef** [comment]
This is now finished
