### ISSUE TITLE
Send extra prekey bundles with FR handshake

### ISSUE THREAD

**Issue by BeaudanBrown** [loki-project/session-desktop#367]
As we start looking in to multi device capabilities, it could make for a better UX to have extra prekey bundles ahead of time when a friend request is completed
That way the participants of the friend request would be able to transfer these prekey bundles to their other devices to remove the need to perform a new friend request exchange with each of their contacts

**Comment by KeeJef** [comment]
Is this still relevant?

**Comment by BeaudanBrown** [comment]
Will need to have some conversations about it, might be overengineering the issue
