### ISSUE TITLE
Desktop keyboard movement by word not working normally

### ISSUE THREAD

**Issue by jagerman** [loki-project/session-desktop#630]
**Describe the bug**

On my linux desktop when I try to use Ctrl-Left/Ctrl-Right to move through the text by word I don't get anything (it moves as if I'm not holding Ctrl).  Alt-Left/Alt-Right *does* move by word, but my muscle memory can't deal with that (because no other apps on linux/windows use alt for that).

**To Reproduce**

Type multiple words, press Ctrl-LeftArrow and expect to move left by a word.

* Device: PC
* OS: Debian sid
* Loki messenger Version or Git commit hash: v1.0.0-beta8

**Comment by konstantinullrich** [comment]
HI @jagerman, does this problem still occur on v1.0.4, because I wasn't able to reproduce this problem.

**Comment by jagerman** [comment]
Yeah, looks like this is working now.  (#631 which is how I really noticed this is still broken though).
