### ISSUE TITLE
Remove conversation of unpaired device

### ISSUE THREAD

**Issue by sachaaaaa** [loki-project/session-desktop#666]
Issue:
When unpairing a device, then pairing a new one, the new device will see the old device in the sync'ed contact list.

Steps to reproduce:
- Pair `Primary Device` to `Secondary Device #1`
- unpair  `Secondary Device #1` (gets nuked)
- Pair `Secondary Device #2` with `Primary Device`
- Notice how `secondary device #2` shows an unexpected contact in the conversation list. The pubkey of that contact is the hidden pubkey of the `secondary device #1`.

Most probably, `Primary Device` should simply remove any information about `Secondary Device #1` during the unpairing, to prevent that pubkey being synced over when pairing `Secondary Device #2`.

**Comment by Bilb** [comment]
Closing this for now as we disabled multi device until it is more reliable
