### ISSUE TITLE
Remove translation files

### ISSUE THREAD

**Issue by KeeJef** [loki-project/session-desktop#708]
Signal is still mentioned in various places in the translation files, we also don't know if these translations will still be accurate considering the parts of the application we have changed, and any of the new strings we have added will be missing translations and be in English only.

I think we should remove the translation files for the Session re-branding and roll with English only, we can translate Session into more languages post launch

**Comment by 1000i100** [comment]
> I think we should remove the translation files for the Session re-branding and roll with English only, we can translate Session into more languages post launch

Is launch done, and translation time back ?

**Comment by KeeJef** [comment]
we will need to revisit our desktop translation strategy, right now we are focusing on Android translations as this is the most used platform

**Comment by 1000i100** [comment]
No problem, it was just to check if translation is in your focus ;)
