### ISSUE TITLE
Desktop: window resize needs a redraw/paint

### ISSUE THREAD

**Issue by neuroscr** [loki-project/session-desktop#755]
<img width="1290" alt="Screen Shot 2020-01-29 at 1 15 37 AM" src="https://user-images.githubusercontent.com/1224671/73343146-e7a05b00-4234-11ea-9ace-7e15c61fdc79.png">

As seen above, after resizing a window on desktop, the grey bars on the left no longer extend all the way down.

**Comment by Bilb** [comment]
Should be fixed, feel free to reopen if not
