### ISSUE TITLE
Desktop: Group detail options, getting pointer but clicking does nothing

### ISSUE THREAD

**Issue by neuroscr** [loki-project/session-desktop#756]
<img width="311" alt="Screen Shot 2020-01-29 at 1 29 04 AM" src="https://user-images.githubusercontent.com/1224671/73344215-cf314000-4236-11ea-9610-7fda92772155.png">

click notifications or disappearing messages does nothing. Suggest changing cursor to not be a pointer (hand).

**Comment by Bilb** [comment]
Should be fixed (hidden for now) since https://github.com/loki-project/session-desktop/pull/854
