### ISSUE TITLE
Desktop: selection mode can click on things that prevent you selecting image messages

### ISSUE THREAD

**Issue by neuroscr** [loki-project/session-desktop#795]
**Describe the bug**
When in message selection mode, profile and image preview links should not work, they should select the message

**To Reproduce**
Find open group message with image and a text message, click on text message, it should enter selection mode, then click on the image or their profile picture.

**Screenshots or Logs**
can provide if needed

**Other information (please complete the following information):**

* Device: Mac
* OS: 10.14
* Session Version or Git commit hash: a8f1cb9359dc85e61e2e533e3d4dce01a8bd2d37

**Comment by neuroscr** [comment]
also link opens through the selection mode

**Comment by Bilb** [comment]
About the link here is a fix : https://github.com/loki-project/session-desktop/pull/920
Keep that issue opened until the image selection is fixed too
