### ISSUE TITLE
Desktop: Can't copy text segment from message

### ISSUE THREAD

**Issue by neuroscr** [loki-project/session-desktop#801]
**Describe the bug**
Can't copy paste text segment

**To Reproduce**
Try to select a word by dragging the mouse or double clicking

**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.

**Other information (please complete the following information):**

* Device: Mac
* OS: MacOS 10.14
* Session Version or Git commit hash: 69fe066bcc983e1b446cdf5f25900356ef2df28f

**Comment by jagerman** [comment]
Confirmed on linux.

**Comment by Bilb** [comment]
Fixed in https://github.com/loki-project/session-desktop/pull/851
