### ISSUE TITLE
Windows: Bug Exiting Settings and Clicking the Group or Chat Icon Indicates a Highlighted Channel

### ISSUE THREAD

**Issue by necro-nemesis** [loki-project/session-desktop#817]
After closing the settings menu when clicking on either the group or chats icons a channel is highlighted but not rejoined. This leaves the user waiting to see if the messages will repopulate from the highlighted channel but they do not repopulate. A more appropriate behavior would be to highlight and return to last used chat before entering settings or not have the channel highlighted thus letting the user know they have to click on a channel to repopulate the channel. The current behavior leaves the channel highlighted and the chat window is only populated with a Session logo. i.e the highlighted channel is misleading that a channel is active when it is not.

**Comment by KeeJef** [comment]
ill link this to #847

**Comment by necro-nemesis** [comment]
Linked to comments in #847. Closed for clarity.
