### ISSUE TITLE
Linux: Drop frame min height to 720 pixels or less to support lower screen resolutions

### ISSUE THREAD

**Issue by necro-nemesis** [loki-project/session-desktop#820]
As the title says I tested on an older laptop with a lower res screen. Controls are buried in the bottom. Cannot scrunch the vertical down to pull the bottom into frame and likely due to a higher than 720 minimum pixel height, the full screen option is greyed out due to it being vertically out of range.

**Comment by pinkprius** [comment]
I have the same problem, this isn't even an "older laptop", but 1366x768 pixels is still fairly common and won't fit the client.

**Comment by jagerman** [comment]
Laptop manufacturers should be heavily fined for producing a laptop screen with such a resolution in laptop model released in a year that starts with a "2".

**Comment by necro-nemesis** [comment]
This one has no camera. Now they charge extra for that feature.

**Comment by necro-nemesis** [comment]
I just upgraded to v1.0.2 in which the screen height issue I was encountering and generated this report looks to be resolved in Linux desktop.

**Comment by neuroscr** [comment]
minimum height is now 880, we need to relayout the closed group page. But our goal is to make 720 possible in the future.

**Comment by hueq** [comment]
I experienced this issue with Session 1.0.6 in Tails. I can't see composed messages as I type them at all because the window height is too large. Sorry I don't remember the display resolution.
