### ISSUE TITLE
no translation for secretPrompt

### ISSUE THREAD

**Issue by neuroscr** [loki-project/session-desktop#822]
**Describe the bug**
`i18n: Attempted to get translation for nonexistent key 'secretPrompt'`

Just sets the title of the toast but probably should be set... to what I'm not sure, if I knew, I'd just fix it.

**To Reproduce**
try to pair device on desktop

**Screenshots or Logs**
```
./ts/components/session/RegistrationTabs.tsx:        title: `${window.i18n('secretPrompt')} ${words}`,
```

**Other information (please complete the following information):**

* Device: Linux
* OS: Debian-based
* Session Version or Git commit hash: 1.0

**Comment by vincentbavitz** [comment]
Fixed.
