### ISSUE TITLE
You can create a closed group with no members

### ISSUE THREAD

**Issue by neuroscr** [loki-project/session-desktop#830]
**Describe the bug**
You can create a closed group with no members.

No sure we want this.

**To Reproduce**
Create a closed group

**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.

**Other information (please complete the following information):**

* Device: Unknown
* OS: Unknown
* Session Version or Git commit hash:

**Comment by KeeJef** [comment]
Assigning this to Brian

**Comment by jian10au** [comment]
> **Describe the bug**
> You can create a closed group with no members.
> 
> No sure we want this.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> Create a closed group
> 
> **Screenshots or Logs**
> If applicable, add screenshots or log files to help explain your problem.
> 
> **Other information (please complete the following information):**
> 
> * Device: Unknown
> * OS: Unknown
> * Session Version or Git commit hash:

Hey Ryan, 
I cannot reproduce the same issue in desktop. 
It seems I had to add a member to create a group successfully.
Could you provide me a screen shot for a group without a member.
Thanks.
Brian

**Comment by vincentbavitz** [comment]
Fixed.
