### ISSUE TITLE
disappearing messages needs some way of indicating what your current setting is

### ISSUE THREAD

**Issue by neuroscr** [loki-project/session-desktop#831]
**Describe the bug**
Disappearing messages needs some way of indicating what your current setting is because I have no idea what it defaults to

**To Reproduce**

**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.

**Other information (please complete the following information):**

* Device: [e.g. PC, Mac]
* OS: [e.g. Ubuntu 16.04, Windows 10]
* Session Version or Git commit hash:

**Comment by Bilb** [comment]
Don't you see that settings in the conversation header? If nothing is there, it means disappearing message are disabled.
![disappearing](https://user-images.githubusercontent.com/1544279/74499961-83baa980-4f39-11ea-920e-0df97e88c291.png)
