### ISSUE TITLE
Update group buttons look awkward

### ISSUE THREAD

**Issue by neuroscr** [loki-project/session-desktop#832]
**Describe the bug**
 the okay and cancel button may need some adjustment

**To Reproduce**

**Screenshots or Logs**
![screenshot](https://media.discordapp.net/attachments/482048282315718657/675428037986222090/unknown.png)

**Other information (please complete the following information):**

* Device: [e.g. PC, Mac]
* OS: [e.g. Ubuntu 16.04, Windows 10]
* Session Version or Git commit hash:

**Comment by KeeJef** [comment]
Assigning this to Brian

**Comment by KeeJef** [comment]
this is the same for the invite friends to open group modals with an indented scroll bar
![image](https://user-images.githubusercontent.com/27277414/74992750-22488c80-549d-11ea-8a36-b96ecb0c874c.png)

**Comment by jian10au** [comment]
![image](https://user-images.githubusercontent.com/48778096/74999041-9dff0500-54ae-11ea-8488-73357e9dc639.png)
Cannot reproduce the same issue, might already have been fixed in the latest release?

**Comment by Bilb** [comment]
Fixed since a while ago 
![image](https://user-images.githubusercontent.com/1544279/103611970-8e2dc980-4f77-11eb-8a23-911627d88529.png)
