### ISSUE TITLE
Don't make me remember what weekday it is

### ISSUE THREAD

**Issue by jagerman** [loki-project/session-desktop#849]
Instead of showing "THU 9:36 PM" we could show "TODAY 9:36 PM" or maybe just "9:36 PM" (with the day added only for messages that aren't today).

**Comment by KeeJef** [comment]
@vincentbavitz take note of this with the message view redesign

**Comment by Bilb** [comment]
We are now displaying a `2 days ago` on the message metadata. 
Are you talking about the tooltip with the details of the timestamp? If so, it makes sense to me to have the full details on the tooltip only but not on the message itself.

**Comment by jagerman** [comment]
At the time I don't think we showed the relative time but always something like "WED 1:23 PM", so I think whenever messages switched to relative time solved this.
