### ISSUE TITLE
Open Group gets duplicates

### ISSUE THREAD

**Issue by neuroscr** [loki-project/session-desktop#866]
**Describe the bug**
Getting duplicate message events in open groups after being connected for long periods of time.

**To Reproduce**
It's unclear, just leave client open unattended for hours.

**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.
![Screen Shot 2020-02-16 at 8 36 01 PM](https://user-images.githubusercontent.com/1224671/74624103-0a1ee900-50fc-11ea-8725-7adb81dd329f.png)

**Other information (please complete the following information):**

* Device: Mac
* OS: 10.14
* Session Version or Git commit hash: 1.0.1

**Comment by KeeJef** [comment]
Ran into another user getting this today, will try and get details

**Comment by neuroscr** [comment]
I think I have a fix, just waiting for some time to actually test it before committing it up
