### ISSUE TITLE
Desktop app crashes with segmentation fault on Fedora 31

### ISSUE THREAD

**Issue by clmbmb** [loki-project/session-desktop#875]
**Describe the bug**
Running the AppImage on Fedora 31 fails with segmentation fault.

**To Reproduce**
1. Download package from site.
2. Make package executable (`chmod +x session-messenger-desktop-linux-1.0.2.AppImage`)
3. Run the package (`./session-messenger-desktop-linux-1.0.2.AppImage`)

**Screenshots or Logs**
```
$ ./session-messenger-desktop-linux-1.0.2.AppImage
Set Windows Application User Model ID (AUMID) { appUserModelId: 'org.whispersystems.session-messenger-desktop' }
NODE_ENV production
NODE_CONFIG_DIR /tmp/.mount_sessioHIEmIR/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME undefined
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
userData: /home/radam/.config/Session
config/get: Successfully read user config file
config/get: Did not find ephemeral config file, cache is now empty object
making app single instance
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
{"name":"log","hostname":"whale","pid":108929,"level":30,"msg":"app ready","time":"2020-02-18T09:08:25.037Z","v":0}
{"name":"log","hostname":"whale","pid":108929,"level":30,"msg":"starting version 1.0.2","time":"2020-02-18T09:08:25.038Z","v":0}
{"name":"log","hostname":"whale","pid":108929,"level":30,"msg":"updateSchema: Current schema version: 0; Most recent schema version: 11; SQLite version: 3.20.1; SQLCipher version: 3.4.2;","time":"2020-02-18T09:08:25.055Z","v":0}
{"name":"log","hostname":"whale","pid":108929,"level":30,"msg":"updateToSchemaVersion1: starting...","time":"2020-02-18T09:08:25.055Z","v":0}
Segmentation fault (core dumped)
```

**Other information (please complete the following information):**

* Device: Thinkpad T480
* OS: Fedora 31 (up to date)
* Session Version or Git commit hash: 1.0.2

**Comment by steve12l** [comment]
I have exactly the same problem : 

**Describe the bug**
Running the AppImage on Fedora 31 fails with segmentation fault.

**To Reproduce**

    Download package from site.
    Make package executable (chmod +x session-messenger-desktop-linux-1.0.2.AppImage)
    Run the package (./session-messenger-desktop-linux-1.0.2.AppImage)


./session-messenger-desktop-linux-1.0.2.AppImage
Set Windows Application User Model ID (AUMID) { appUserModelId: 'org.whispersystems.session-messenger-desktop' }
NODE_ENV production
NODE_CONFIG_DIR /tmp/.mount_sessioNDKnFh/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME undefined
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
userData: /home/SteveL/.config/Session
config/get: Successfully read user config file
config/get: Did not find ephemeral config file, cache is now empty object
making app single instance
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
{"name":"log","hostname":"phantom","pid":88832,"level":30,"msg":"app ready","time":"2020-02-20T14:49:41.702Z","v":0}
{"name":"log","hostname":"phantom","pid":88832,"level":30,"msg":"starting version 1.0.2","time":"2020-02-20T14:49:41.703Z","v":0}
{"name":"log","hostname":"phantom","pid":88832,"level":30,"msg":"updateSchema: Current schema version: 0; Most recent schema version: 11; SQLite version: 3.20.1; SQLCipher version: 3.4.2;","time":"2020-02-20T14:49:41.791Z","v":0}
{"name":"log","hostname":"phantom","pid":88832,"level":30,"msg":"updateToSchemaVersion1: starting...","time":"2020-02-20T14:49:41.793Z","v":0}
Erreur de segmentation (core dumped)

**Comment by majestrate** [comment]
if i recall, appimage segfaulting on fedora are a common issue on fedora.

**Comment by despair86** [comment]
yes the appimage was compiled on ubuntu 18.04, where both openssl 1.0 and 1.1 are present, and electron-builder seems to have picked the older revision, while fedora core 31 only ships with openssl 1.1 - openssl does NOT have a stable ABI across minors, only across patch releases

my current workaround is
```
# yum install compat-openssl10
$ LD_PRELOAD=/lib64/libcrypto.so.1.0.2o ./session-messenger-desktop-linux-1.0.2.AppImage
```
ideally we _should_ just throw in a copy of openssl 1.0 into the appimage and follow its patch releases (fedora has 1.0.2o, current is 1.0.2u)

-a native dev

**Comment by despair86** [comment]
update: some system library that electron depends on is linked against openssl 1.1 on fedora, but uses an alternative crypto backend on ubuntu. this causes all references to openssl functions inside the electron binary to be resolved against the system library instead of the internal symbols

**Comment by despair86** [comment]
https://github.com/signalapp/Signal-Desktop/issues/2787 is related

**Comment by KeeJef** [comment]
There is a new release out 1.0.3 here, https://github.com/loki-project/session-desktop/releases/tag/v1.0.3

This should fix the Fedora issues
