### ISSUE TITLE
MacOs desktop : feature requests

### ISSUE THREAD

**Issue by ihubgit** [loki-project/session-desktop#883]
Hi, haven't tested out the iOs version yet, but the following things cross my mind that could be considered feature-requests :

1. rich text
bold, underline etc, but with icons and not markdown commands

2. edit text message
after being sent, instead of posting a new msg with the corrections

3. stretch-to-fit messages
terminology taken from Wickr : for longer messages, the ability for the text messages to take up the whole width of the screen and not just half of them. Would be nice to be able to do this for individual messages only (with intuitive UI, f.ex. ability to simply drag edge of the text bubble to other side)

4. in-app updates
for the moment have to regularly consult Session webpage

5. drag&drop attachments

6. advanced search
sort by date, author, keywords, etc...

7. my messages / replies
for easily retrieving own contributions to given discussion

8. recall messages
i.e. ability to remotely delete one's own sent messages from the device(s) of the recipient. Feature available in Wickr.

9. bootstrap options for bypassing firewall (and censorship)
similar to the obfs4 bridges from Tor or snowflake plugin

**Comment by ihubgit** [comment]
10. internal email
only works inside the Session/Loki platform. Easier for longer messages with rich text than the IM layout... Not necessarily with bridge to regular clearnet email solutions.

**Comment by ihubgit** [comment]
11. ability for picking other fond that one provided
just tested out for RL language and provided font is horrible...

**Comment by ihubgit** [comment]
12. ability to unsubscribe from the "Session updates" channel inside Session
prefer other platforms for remaining informed, such as Reddit.
At least to be able to _hide_ the channel from the view of the user

**Comment by neuroscr** [comment]
Would you please file one issuer per item, so we can discuss and close them as we address them

**Comment by ihubgit** [comment]
how do i delete first post?

**Comment by neuroscr** [comment]
You can’t, just have to close it. I’ll do that now
