### ISSUE TITLE
Drag and Drop Attachment

### ISSUE THREAD

**Issue by ihubgit** [loki-project/session-desktop#888]
Allow attachments to be sent by dragging the attachment into the message view

**Comment by User486375** [comment]
@vincentbavitz Isn't this a duplicate of #703? Also, without having a to make another issue, could the ability to copy and paste (ctrl c ctrl v) be included in this issue? Considering both are currently possible in signals desktop client, I'm assuming it's not a hard fix.

**Comment by KeeJef** [comment]
Yes, Duplicate of #703
