### ISSUE TITLE
Unhandled Promise Rejection error when updating

### ISSUE THREAD

**Issue by ihubgit** [loki-project/session-desktop#893]
Hi again. Using the desktop app (1.0.2) I've been running into the following (minor) issues :

updating from 1.0.1 to 1.0.2 yields Unhandled Promise Rejection error
![Capture d’écran 2020-02-17 à 08 35 46](https://user-images.githubusercontent.com/47977025/74939382-0e931c80-53f0-11ea-9d27-3dcd034e2f86.jpg)

**Comment by KeeJef** [comment]
Adding to this i had the same Error when upgrading

```
Unhandled Promise Rejection

Error: Object has been destroyed
    at WebContents.send ([REDACTED]\electron.asar\browser\api\web-contents.js:112:15)
    at EventEmitter.ipcMain.on ([REDACTED]\app.asar\app\attachment_channel.js:45:20)
```

**Comment by sounak98** [comment]
I am going through the codebase, will submit a PR when done.

**Comment by konstantinullrich** [comment]
> If you close a browser window it will be destroyed, so you can't hide or show it again after that.
(Source: https://stackoverflow.com/a/38342337)
I guess that is the problem. I'll take a lock and try to fix it.

**Comment by konstantinullrich** [comment]
@KeeJef or @ihubgit Can you please provide steps to reproduce the error.

**Comment by neuroscr** [comment]
Bump the package.json version, it will trigger the bug

**Comment by konstantinullrich** [comment]
```
cleanup orphaned attachments error: TypeError: Cannot read property 'get' of null
  at getMessageCount ([REDACTED]\\session-desktop\\app\\sql.js:2025:24)
  at Object.removeKnownAttachments ([REDACTED]\\session-desktop\\app\\sql.js:2830:23)
  at cleanupOrphanedAttachments ([REDACTED]\\session-desktop\\main.js:822:43)"
```
I think this is the error, wich causes the **Object has been destroyed**-Error

**Comment by neuroscr** [comment]
yea the db object is destroyed at the point "cleanup orphaned attachments" is ran. So it's an order of operations issue

**Comment by konstantinullrich** [comment]
The error is caused by the call of `cleanupOrphanedAttachments` on line 435 in `js/background.js`
