### ISSUE TITLE
Add limited three dot menu to Friend request messages

### ISSUE THREAD

**Issue by ihubgit** [loki-project/session-desktop#894]
while i can understand it's a special kind of message, why overrides it the above ?

**Comment by KeeJef** [comment]
Not sure what this related to, can you please give a better explanation

**Comment by ihubgit** [comment]
Well, basically, when first posting someone the poster isn't always aware that this is a special kind of message (a friendly invite) and he basically starts typing the message he had in mind (like a question or so). Now, it turns out the friendly invite has some unique properties, basically not allowing any kind of action being taken upon (like get info, no suspension dots with drop down menu, nor being deleted). I for one would like to be able to delete it after "handshaking" is done, as is possible for any other message.

**Comment by Bilb** [comment]
I cannot reproduce this issue. I guess it has been fixed already. The triple dots is not visible when hovering a `sent` or `received` friend request
