### ISSUE TITLE
Better distinguish between local and remote delete

### ISSUE THREAD

**Issue by ihubgit** [loki-project/session-desktop#895]
ok this was in the public chat channel. Because of firewall issue I the msg didn't go through, but I was unable to delete it from the suspension dots menu, only when selecting the msg bubble itself and hitting dedicated delete button at top menu

**Comment by Bilb** [comment]
We had a few issues with the contextmenu. We fixed most of them on the v1.4.3 and I believe this error is fixed now. 
Feel free to reopen if needed
