### ISSUE TITLE
MacOs desktop : deleting sent message through dedicated delete button yields permission error

### ISSUE THREAD

**Issue by ihubgit** [loki-project/session-desktop#897]
this one is the other way around. On successfully sent msg, deletion works through suspension dots menu, but when using delete button getting permission error, as if I wanted to delete someone else's message !
![Capture d’écran 2020-02-12 à 13 19 41](https://user-images.githubusercontent.com/47977025/74947390-10aea880-53fb-11ea-8054-21123c9e6968.jpg)

**Comment by KeeJef** [comment]
closing for #895
