### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by ihubgit** [loki-project/session-desktop#899]
Hi, been using the desktop app for a few days and looks promising. Did scroll through first 3 pages here, so I hope I'm not duplicating any request. Just jotting down a small list of UI suggestions if u guys don't mind :

light theme
possibility of having stg else than the dark scheme...

**Comment by KeeJef** [comment]
This work is ongoing

**Comment by nunbit** [comment]
Yes. Also please light it up. Love overall design just hate white text on black for eyes.

**Comment by kmltdr** [comment]
Shouldn't this issue be closed? There is light mode in 1.3.1
