### ISSUE TITLE
Remove redundant search icon in message view

### ISSUE THREAD

**Issue by ihubgit** [loki-project/session-desktop#903]
two "magnifying glass" icons for searching

**Comment by KeeJef** [comment]
Can you please provide a screenshot, not sure what you are referring to

**Comment by ihubgit** [comment]
![Capture d’écran 2020-02-21 à 10 06 43](https://user-images.githubusercontent.com/47977025/75019883-f542ac80-5491-11ea-9062-0f29f867eb0b.jpg)
Why putting search icon on top right, if only function is to forward to search bar on left side menu? Seems redundant and confusing to me.

**Comment by konstantinullrich** [comment]
I would be glad to look into the problem

**Comment by konstantinullrich** [comment]
Implemented in #921.

**Comment by KeeJef** [comment]
The Gitcoin bounty will be paid out when #921 is reviewed and merged

**Comment by konstantinullrich** [comment]
The PR(#921) is merged you can resolve this issue @KeeJef
