### ISSUE TITLE
MacOS desktop : feature request : save state unfinished message

### ISSUE THREAD

**Issue by ihubgit** [loki-project/session-desktop#908]
Ok, so I was starting to type a message in the text bar, but without sending it yet and head over to the left menu bar to check out something. Now, when I head back to the chat channel to continue my message, I found out it hadn't been automatically saved and got an empty text box so I could start all over again...
Would be nice to have Session save that unfinished state of the message...

**Comment by KeeJef** [comment]
Closing as a duplicate of  #847
