### ISSUE TITLE
"Copy text" buttons not working in open groups

### ISSUE THREAD

**Issue by ihubgit** [loki-project/session-desktop#909]
Hi, tried to "copy text" both through right clicking speech bubble and suspension dots menu and when pasting doesn't work...
Ps: when someone shares a URL as speech bubble, Session might intelligently identify this as such and present appropriate actions when right clicking, such as 'copy url' or better 'open in xxx browser'... (the latter of course can be accomplished by simply clicking on the link).

**Comment by KeeJef** [comment]
It seems copy text is not working in the context of public chats

**Comment by Bilb** [comment]
Should be fixed by https://github.com/loki-project/session-desktop/pull/935/files
