### ISSUE TITLE
Is session TOFU?

### ISSUE THREAD

**Issue by erotavlas-turbo** [loki-project/session-desktop#912]
Hi,
I recently discovered session and I read that is based on signal messenger. Signal protocol provides e2e encryption, but it is [Trust On First Use (TOFU)](https://en.wikipedia.org/wiki/Trust_on_first_use). So if you cannot meet in person your interlocutors (any other channel is not secure), it requires trust on the server.
How does session think to solve this problem? What about using the loki network to store public key in order to bypass such problem?
Thank you

**Comment by KeeJef** [comment]
Session is TOFU primarily because you need to bootstrap into the network of Service Nodes, to do this we have some pre-configured seed nodes and a hardcoded public key in the Session client, once connected to the Seed Nodes they give you a list of all of the Service Nodes in the network.

There isn't really a way to get around this first step, which even Bitcoin requires. Past that point any conversations you have are not trust on first use, since you always add a user with their Session ID (Long term public key), and can immediately, programmatically, authenticate their responses.

**Comment by erotavlas-turbo** [comment]
> Session is TOFU primarily because you need to bootstrap into the network of Service Nodes, to do this we have some pre-configured seed nodes and a hardcoded public key in the Session client, once connected to the Seed Nodes they give you a list of all of the Service Nodes in the network.

Well, if the public keys are hardcoded into the client, session is not TOFU since the endpoints (seed nodes) are known and reliable.

> There isn't really a way to get around this first step, which even Bitcoin requires. Past that point any conversations you have are not trust on first use, since you always add a user with their Session ID (Long term public key), and can immediately, programmatically, authenticate their responses.
Great, I need a confirmation.

**Comment by erotavlas-turbo** [comment]
Hi,
I have to reopen the question. Can you explain me why session allow to verify user safety number in the same manner of signal? Is that a typo from the fork? Or is session not TOFU?
![image](https://user-images.githubusercontent.com/11888321/75788132-121b9180-5d68-11ea-9952-107efa4f7774.png)

**Comment by KeeJef** [comment]
Ill need to verify that we have removed all of the relevant Signal code, but in Session you cannot change your long term keys during a conversation. When you add a user you must use their long term public key, and any attempt to change this during a conversation will lead to a new friend request/conversation and the user will need to decide whether to trust this person. 

This is different to Signal where you must trust that the phone number - public key mapping is correct and this can change at any time during the conversation. Safety numbers have been kept in Session for cases where users would want to easily verify long term public keys with another user they have not met outside of the application.

**Comment by erotavlas-turbo** [comment]
Thank you for you reply. Now it is clear. Good work.
