### ISSUE TITLE
Windows Defender detects Windows installer as PUA:Win32/CoinMiner

### ISSUE THREAD

**Issue by zndnrc** [loki-project/session-desktop#939]
**Describe the bug**
Windows Defender detects the win installer as PUA:Win32/CoinMiner

**To Reproduce**
Download Windows installer

**Screenshots or Logs**
![image](https://user-images.githubusercontent.com/12544693/75687934-df599680-5c9e-11ea-9798-cce8692217d1.png)

**Other information (please complete the following information):**

* Device: PC
* OS: Windows 10
* Session Version or Git commit hash: desktop version 1.0.2

**Comment by KeeJef** [comment]
This is a false flag, i assume that there is detection of SHA-512 which we use for the small PoW which is attached to each message. We are not using Session to mine cryptocurrencies though

**Comment by nicekon** [comment]
@KeeJef I am having this problem in my application as well. It hurts. If you have solved this problem, can you tell me how?

**Comment by KeeJef** [comment]
try reporting it as a false detection here https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by Zifrian** [comment]
Hello, I realize this is an old thread but I have a windows app with this error and wondering if you ever figured out how to get rid of it. Was it the SHA-512 use? I use that as well for doing a PKCE call to a video game server for character info. This error started popping up during the time I started using this as well. If so, this might be the nugget I've been looking for to solve this problem.

**Comment by KeeJef** [comment]
@Zifrian I haven't seen it get flagged on Windows for a while, is this happening to other people aswell?
