### ISSUE TITLE
possible password length problem

### ISSUE THREAD

**Issue by boistordu** [loki-project/session-desktop#940]
**Describe the bug**
a problem between the unlocking window which accept my password and the popup to reveal my seed who asks for my password and doesn't accept it.
**To Reproduce**
generate a password of 64 char with all character allowed with a password generator, use it for create your session, then try to reveal your seed with it.
**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.
not relevant at this point.
**Other information (please complete the following information):**
maybe specify the password length in the FAQ or the docs.
* Device: [e.g. PC, Mac] PC
* OS: [e.g. Ubuntu 16.04, Windows 10] Windows 10
* Session Version or Git commit hash: release v.1.0.2

**Comment by vincentbavitz** [comment]
Hey,
Please keep in mind that MAX_PASSWORD_LENGTH is 32.
Pasting a password larger than this will have Session save the first 32 characters as your password instead.
