### ISSUE TITLE
Linking accounts takes ages and never finishes

### ISSUE THREAD

**Issue by szmarczak** [loki-project/session-desktop#943]
The title says for itself

* Device: Linking a PC to a smartphone
* OS: Solus 4.1, Android 9
* Session Version or Git commit hash: Solus: `1.0.2` Android: `1.0.4`

**Comment by Niek** [comment]
Same here... the app hangs when linking an existing device.

**Comment by KeeJef** [comment]
Are you making sure that you are on the device linking screen on the secondary device? the secondary device can also only be linked from the onboarding screen, as in it needs to be a fresh account.

**Comment by szmarczak** [comment]
Yep, I did follow all the steps.

**Comment by Hoimar** [comment]
I'm affected by this too. Created an account on Session Android 1.0.5, then wanted to link it using Session Desktop 1.0.2 following the required steps exactly, but I never get a notification on mobile, and the desktop app keeps showing me a loading bar.
See also #942.

Cheers

**Comment by gt7599a** [comment]
Same problem

1. Created session ID on Android Session v 1.0.5
2. Attempt to link to account on PC running session-messenger-desktop-win-1.0.3 using the "Link Device to Existing Session ID" 
3. The Desktop client generates a three word secret, but nothing ever appears to happen on the Android client. 

![image](https://user-images.githubusercontent.com/12285358/76045221-635d9800-5f97-11ea-997f-9b8dea85df54.png)

**Comment by Mikunj** [comment]
On your mobile device, do you have the linking dialog open? You can go it by going to Settings > Devices > Link a new device. When you have it open, send a request from the desktop client to the mobile and see if that works.

**Comment by szmarczak** [comment]
Tested again on Windows 10 & Session v1.0.4, nothing has changed. Linking takes ages yet again.

**Comment by Hoimar** [comment]
For me it works now, even before the newly released updates. So creating an ID on Session Android 1.0.5, then linking to it with Session Desktop 1.0.2 on Linux only took a few seconds to complete
(don't know if the updates change this, e.g. make it even faster).

**Comment by gt7599a** [comment]
I was able to link from android to pc, but it took a very long time, I
didn't time it but probably 5-10 minutes after initiating the link I looked
back to see it had completed.

Ed

**Comment by Mikunj** [comment]
Can you check to see if this is still a problem in the latest android and desktop versions? Upon clicking authorise on android you might have to wait around 10 seconds for it to link the device properly.

**Comment by szmarczak** [comment]
Checked again, nothing pops up.

**Comment by Mikunj** [comment]
Okay, i'll keep looking into this but i haven't had much luck reproducing it :(

**Comment by szmarczak** [comment]
Try spamming the "Link Device button". Alternatively do this:

1. Do NOT open the Devices tab on Android.
2. Click "Link Device" on Desktop, then cancel by switching to the "Create an account" tab.
3. Switch to the Devices tab on Android and click "Link Device" on Android.
4. Switch back to the Sign In tab on Desktop.
5. Click "Link Device" again on Desktop.

**Comment by KeeJef** [comment]
sounds like this might be related to threading issues on Android according to @gmbnt

**Comment by szmarczak** [comment]
Tested again on Windows 10 (Session 1.0.5) and Android 9.0 (Session 1.0.9). The issue seems to be fixed.

**Comment by szmarczak** [comment]
I'll test again on Linux and will let you know.

**Comment by szmarczak** [comment]
I think it is fixed now. The linking takes 5s ± 2s, but I don't mind waiting.
