### ISSUE TITLE
Cannot unlink a device

### ISSUE THREAD

**Issue by szmarczak** [loki-project/session-desktop#944]
Please see #943 first. I tried linking 3 or 4 four times, and the notification appeared only once after ~10s or more. I confirmed the link, then I saw the Linux app still shows it's unlinked so I wanted to unlink the Linux device using my Android. When I click "Unlink device" it shows "Cannot unlink device."

**Comment by KeeJef** [comment]
Is this working now? some users reported that device linking was now working for them

**Comment by szmarczak** [comment]
I'll try again and will let you know today.

**Comment by szmarczak** [comment]
It works now (there's a successful toast notification) but the device doesn't disappear from the list. I think it's a bug. It disappears when you restart the app tho.
