### ISSUE TITLE
Notifications Incorrectly reference OWS 

### ISSUE THREAD

**Issue by KeeJef** [loki-project/session-desktop#952]
![image](https://user-images.githubusercontent.com/27277414/75960447-30be8b80-5f14-11ea-9b60-36404f9dde39.png)

Session is not a part of Open whisper systems

**Comment by neuroscr** [comment]
should we use `org.getsession` or `network.loki` prefix?

**Comment by Mikunj** [comment]
It should be the one we use in `package.json`

**Comment by neuroscr** [comment]
`com.loki-project.messenger-desktop` was the only one I saw in package.json, hrm main.js currently would make that `com.loki-project.session-desktop`. I really hate using com.loki-project since we don't own that domain.
