### ISSUE TITLE
Dragging Zoom Makes the GUI Freak out

### ISSUE THREAD

**Issue by Skelaton4** [loki-project/session-desktop#953]
**Describe the bug**
Dragging the Zoom feature makes the entire Session GUI freak out. 

**To Reproduce**
Drag Zoom in Session 1.0.3

**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.
![image](https://user-images.githubusercontent.com/28955674/75991262-37bdad80-5ec4-11ea-81dd-ab88949834de.png)

**Other information (please complete the following information):**

* Device: Computer
* OS: Windows 10 
* Session Version or Git commit hash:Session v1.0.3

**Comment by konstantinullrich** [comment]
Hey @Skelaton4, thank you for the report. I'll take a look
