### ISSUE TITLE
Open group avatar case sensitivity in URLs

### ISSUE THREAD

**Issue by neuroscr** [loki-project/session-desktop#958]
**Describe the bug**
if open server is added in a different case that how we have it store, we get an absolute instead of a relative URL

**To Reproduce**

**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.

**Other information (please complete the following information):**

* Device: [e.g. PC, Mac]
* OS: [e.g. Ubuntu 16.04, Windows 10]
* Session Version or Git commit hash:

**Comment by Bilb** [comment]
Closing as the PR is merged
