### ISSUE TITLE
send-message-container grows but the accompanying Buttons do not.

### ISSUE THREAD

**Issue by konstantinullrich** [loki-project/session-desktop#970]
**Describe the bug**
When you write large messages the send-message-container grows as expected. But the Attachment Button and the Emoji Button do not.

**To Reproduce**
Write a message at least 3x longer than the textbox in a conversation. 

**Screenshots or Logs**
![image](https://user-images.githubusercontent.com/22809542/76314565-59a99c80-62d7-11ea-8ab8-09875f3c3de1.png)

**Other information (please complete the following information):**

* Device: PC
* OS: Windows 10
* Session Version: 1.0.4

**Comment by vincentbavitz** [comment]
Fixed in [SessionCompositionBox.tsx](https://github.com/vincentbavitz/session-desktop/blob/conversationview/ts/components/session/conversation/SessionCompositionBox.tsx)
