### ISSUE TITLE
Request to create a Flatpak

### ISSUE THREAD

**Issue by superuser-miguel** [loki-project/session-desktop#979]
Requesting support for flatpak.

**Comment by schattenpanzer** [comment]
bump

**Comment by schattenpanzer** [comment]
[https://docs.flatpak.org/en/latest/first-build.html](https://docs.flatpak.org/en/latest/first-build.html)

bump

**Comment by KeeJef** [comment]
Yeah we need to take action on this, we we're just waiting for the last release to be finished, which was done a few weeks ago. 

so basically the process is, once approved they will create a repo for us like this, a community member has done all the relevant manifest stuff, so we dont need to worry about that https://github.com/flathub/org.signal.Signal/commit/78bc921044ef661d9c745576c5b8e6bf7f14bbe8

then each release we just update the .deb link, the hash and the version number and commit it to that repo

The PR for inclusion is here https://github.com/flathub/flathub/pull/1564

@Mikunj can you move forward with this?

**Comment by Mikunj** [comment]
Yep i'll take over and start preparing

**Comment by Mikunj** [comment]
It has been added. You can run the following:
```
flatpak remote-add flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub network.loki.Session
```
