### ISSUE TITLE
Constant disk usage

### ISSUE THREAD

**Issue by jagerman** [loki-project/session-desktop#985]
**Describe the bug**
When I open Session (1.0.4, Linux) I get continuous hard drive activity pretty much as soon as it opens, and stays forever until I close it.

**To Reproduce**
Open Session.  Pretty much as soon as it is initialized the write activity starts.

**Screenshots or Logs**
It's most obvious in that it makes my hard drive light flicker away constantly (quite fast -- I'd estimate maybe 5-10 times per second) whenever Session is open (this is on a fast ssd so might be more painful on a HDD).

Looking at the process with `iotop` I see pretty constant disk write access on 3-4 threads all the time:
```
    TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND                
2251979 be/4 jagerman    0.00 B/s  351.86 K/s  0.00 %  0.47 % session-messenger-desktop
2251978 be/4 jagerman    0.00 B/s  276.46 K/s  0.00 %  0.29 % session-messenger-desktop
2251980 be/4 jagerman    0.00 B/s  150.80 K/s  0.00 %  0.16 % session-messenger-desktop
2251977 be/4 jagerman    0.00 B/s   25.13 K/s  0.00 %  0.03 % session-messenger-desktop
```

and these numbers stay there, typically in the 100-400K/s range on three, and 0-100K/s on the fourth one.  (But write level seems to vary across all 4 - it isn't consistent that the '77 thread above stays at the bottom of the list).

**Other information (please complete the following information):**

* Device: [e.g. PC, Mac]
Linux desktop.

* OS: [e.g. Ubuntu 16.04, Windows 10]
Debian sid.

* Session Version or Git commit hash:
1.0.4 (installed via release deb).

**Comment by Bilb** [comment]
I cannot reproduce this issue on Ubuntu. Can you attach some logs got from 
`fatrace |grep -E "electron|session|W"`

My guess is we will get file `db.sqlite` or `db.sqlite-journal` but I have one write every 5-6 seconds only on my end.

**Comment by jagerman** [comment]
This is no longer happening for me with 1.0.5.
