### ISSUE TITLE
Windows install is flagged as containing coinminer

### ISSUE THREAD

**Issue by ForbodingAngel** [loki-project/session-desktop#986]
**Describe the bug**
Coinminer detected in windows install

**To Reproduce**
Download and try to install on windows

**Screenshots or Logs**
https://i.imgur.com/bXiihxh.png

**Other information (please complete the following information):**

* Device: [e.g. PC, Mac]
PC
* OS: [e.g. Ubuntu 16.04, Windows 10]
Windows 10
* Session Version or Git commit hash:
1.0.4

**Comment by KeeJef** [comment]
We have reported this to Microsoft as being falsely detected, however we have not heard back from them regarding any fixes
