### ISSUE TITLE
Cannot paste password into login screen on macOS

### ISSUE THREAD

**Issue by ldub** [loki-project/session-desktop#996]
**Describe the bug**
On the login screen below, on macOS Catalina, I cannot paste by using `cmd+v`. There is also no context menu. This makes it extremely difficult to use Session with a long randomly generated password stored in a password manager.

It is worth nothing that pasting passwords works when in the settings panel inside the app.

**To Reproduce**
1. Open Session
2. Copy password to clipboard from password manager
3. Attempt to paste into the "Type In Your Password" form

**Screenshots or Logs**
![image](https://user-images.githubusercontent.com/3114081/77221192-b3466e00-6b04-11ea-9146-f0f66a3d46f7.png)

**Other information (please complete the following information):**

* Device: Macbook Pro
* OS: macOS Catalina
* Session Version or Git commit hash: 1.0.5

**Comment by vincentbavitz** [comment]
What is the length of your password?
If the text your pasting exceeds the MAX_PASSWORD_LENGTH, the input will not respond.
Currently MAX_PASSWORD_LENGTH is 32 chars.

**Comment by ldub** [comment]
My password is indeed longer than 32 characters. However, I'm not able to paste any test into that screen at all, not even a single character. Also its worth noting that pasting my 34-character password into the settings screen works fine.

Also, I think that the app should prevent me from creating a > 32 char password. Right now it seems to accept a truncated version of my password.

**Comment by vincentbavitz** [comment]
> My password is indeed longer than 32 characters. However, I'm not able to paste any test into that screen at all, not even a single character. Also its worth noting that pasting my 34-character password into the settings screen works fine.
> 
> Also, I think that the app should prevent me from creating a > 32 char password. Right now it seems to accept a truncated version of my password.

Thanks for the info. This is indeed something necessary to review and fix. 
I've assigned myself to this one.
